workspaces:
  hello-world:
    image: ghcr.io/calebfaruki/sycophant-workspace-tools
    tag: latest
    agents:
      - hello-world

chambers:
  workspace-ro:
    image: ghcr.io/calebfaruki/airlock-git:latest
    workspace: hello-world-workspace-data
    workspaceMode: readOnly
    workspaceMountPath: /workspace
