workspaces:
  hello-world:
    image: ghcr.io/calebfaruki/sycophant-mainframe-runtime
    tag: latest
    chambers:
      - workspace-ro

chambers:
  workspace-ro:
    image: ghcr.io/calebfaruki/airlock-git:latest
    workspaceMode: readOnly
    workspaceMountPath: /workspace
