{{- range $component := list "tightbeam" "airlock" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $component }}-scheduling
  labels:
    {{- include "sycophant.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}-ctrl
data:
  scheduling.yaml: |
    tolerations:
      - key: sycophant.io/workload
        operator: Equal
        value: {{ $component }}
        effect: NoSchedule
{{- end }}
