---
apiVersion: v1
kind: ConfigMap
metadata:
  name: toolset-scheduling
  labels:
    {{- include "sycophant.labels" . | nindent 4 }}
    app.kubernetes.io/component: toolset-ctrl
data:
  scheduling.yaml: |
    tolerations:
      - key: sycophant.md/workload
        operator: Equal
        value: toolset
        effect: NoSchedule
