[package]
name = "transponder"
version.workspace = true
edition.workspace = true

[[bin]]
name = "transponder"
path = "src/main.rs"

[dependencies]
hangar-proto = { workspace = true }
tightbeam-proto = { workspace = true }
proto-common = { workspace = true }
airlock-proto = { workspace = true }
mainframe-proto = { workspace = true }
hangar-providers = { workspace = true }
shared = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
tokio-util = "0.7"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
chrono = { version = "0.4", features = ["serde"] }
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
arc-swap = { workspace = true }
tokio-stream = { workspace = true }
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
http-body-util = "0.1"
bytes = "1"

[dev-dependencies]
tempfile = "3"
futures = { workspace = true }

[lints]
workspace = true
