{{- range $name, $ws := .Values.workspaces }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-workspace-data
  labels:
    {{- include "sycophant.workspaceLabels" (dict "context" $ "name" $name) | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
{{- end }}
