[package]
name = "hangar-proto"
version.workspace = true
edition.workspace = true

[dependencies]
base64 = "0.22"
prost.workspace = true
proto-common.workspace = true
transponder-proto.workspace = true
serde_json.workspace = true
hangar-providers.workspace = true
tonic.workspace = true

[build-dependencies]
tonic-build.workspace = true

[lints]
workspace = true
