[package]
name = "tightbeam-controller"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tightbeam-controller"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true
base64.workspace = true
chrono = { version = "0.4", features = ["serde"] }
rustls = { version = "0.23", default-features = false, features = ["aws-lc-rs"] }
clap.workspace = true
ed25519-dalek = { version = "2", features = ["rand_core"] }
futures.workspace = true
http.workspace = true
http-body-util.workspace = true
k8s-openapi.workspace = true
kube.workspace = true
p256.workspace = true
tower.workspace = true
prost.workspace = true
rand = "0.8"
schemars.workspace = true
serde.workspace = true
sha2 = "0.10"
serde_json.workspace = true
serde_yaml = "0.9"
shared.workspace = true
tightbeam-proto.workspace = true
tightbeam-providers.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
tonic-health.workspace = true
tonic-reflection.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
futures.workspace = true
shared = { workspace = true, features = ["test-fixtures"] }
tempfile.workspace = true
tokio-stream = { workspace = true, features = ["net"] }

[lints]
workspace = true
