apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providers.sycophant.md
spec:
  group: sycophant.md
  names:
    kind: Provider
    plural: providers
    singular: provider
    shortNames:
      - tbp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - format
                - secret
              properties:
                format:
                  type: string
                  enum: ["anthropic", "openai", "gemini"]
                baseUrl:
                  type: string
                secret:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    key:
                      type: string
      additionalPrinterColumns:
        - name: Format
          type: string
          jsonPath: .spec.format
